version: '3'
services:
  app:
    build:
      context: .
      dockerfile: agentic-seek-go/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - GIN_MODE=release

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    container_name: ollama

volumes:
  ollama:
